services:
  db:
    image: postgres:14
    container_name: justdone_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: justdone
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
